version: "3.1"
services:
  app:
    container_name: chat-app
    restart: always
    build: .
    ports:
     - '4000:4000'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
     - '27017:27017'
